name: Supporting infrastructure for environments

on:
  push:
    branches: [ main ]
    paths: 
    - '.github/workflows/infrastructure.yml'

env:
  # For creating this secret value, see: https://github.com/marketplace/actions/azure-login#configure-deployment-credentials
  credentials: ${{ secrets.AZURE_CREDENTIALS }}
  resource_group: dev

jobs:

  # Todo: add auto-scaling to App Service plans, although it's unlikely there'll be enough traffic to need it.

  dev-rg:
    name: Dev resource group
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}

    - name: App Service plan
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az appservice plan create --name dev --is-linux --sku p1v2

    - name: Container registry
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          # Admin needs to be enabled for App Service continuous deployment
          az acr create --name govazuredev --sku Standard --admin-enabled true
